      SUBROUTINE DLUM_3(LUM)
C     ****************************************************            
C         
C     Generated by MadGraph5_aMC@NLO v. 2.6.7, 2019-10-16
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     RETURNS PARTON LUMINOSITIES FOR MADFKS                          
C        
C     
C     Process: b g > h > e+ e- e+ e- b NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: c g > h > e+ e- e+ e- c NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: d g > h > e+ e- e+ e- d NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: s g > h > e+ e- e+ e- s NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: u g > h > e+ e- e+ e- u NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: b g > h > mu+ mu- mu+ mu- b NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: c g > h > mu+ mu- mu+ mu- c NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: d g > h > mu+ mu- mu+ mu- d NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: s g > h > mu+ mu- mu+ mu- s NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: u g > h > mu+ mu- mu+ mu- u NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     
C     ****************************************************            
C         
      IMPLICIT NONE
C     
C     CONSTANTS                                                       
C         
C     
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      DOUBLE PRECISION       CONV
      PARAMETER (CONV=389379660D0)  !CONV TO PICOBARNS             
C     
C     ARGUMENTS                                                       
C         
C     
      DOUBLE PRECISION PP(0:3,NEXTERNAL), LUM
C     
C     LOCAL VARIABLES                                                 
C         
C     
      INTEGER I, ICROSS,ITYPE,LP
      DOUBLE PRECISION P1(0:3,NEXTERNAL)
      DOUBLE PRECISION D1,U1,S1,C1,B1
      DOUBLE PRECISION G2
      DOUBLE PRECISION XPQ(-7:7)
C     
C     EXTERNAL FUNCTIONS                                              
C         
C     
      DOUBLE PRECISION ALPHAS2,REWGT,PDG2PDF
C     
C     GLOBAL VARIABLES                                                
C         
C     
      INTEGER              IPROC
      DOUBLE PRECISION PD(0:MAXPROC)
      COMMON /SUBPROC/ PD, IPROC
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
      INTEGER IMIRROR
      COMMON/CMIRROR/IMIRROR
C     
C     DATA                                                            
C         
C     
      DATA D1,U1,S1,C1,B1/5*1D0/
      DATA G2/1*1D0/
      DATA ICROSS/1/
C     ----------                                                      
C         
C     BEGIN CODE                                                      
C         
C     ----------                                                      
C         
      LUM = 0D0
      IF (IMIRROR.EQ.2) THEN
        IF (ABS(LPP(2)) .GE. 1) THEN
          LP=SIGN(1,LPP(2))
          D1=PDG2PDF(ABS(LPP(2)),1*LP,XBK(2),DSQRT(Q2FACT(2)))
          U1=PDG2PDF(ABS(LPP(2)),2*LP,XBK(2),DSQRT(Q2FACT(2)))
          S1=PDG2PDF(ABS(LPP(2)),3*LP,XBK(2),DSQRT(Q2FACT(2)))
          C1=PDG2PDF(ABS(LPP(2)),4*LP,XBK(2),DSQRT(Q2FACT(2)))
          B1=PDG2PDF(ABS(LPP(2)),5*LP,XBK(2),DSQRT(Q2FACT(2)))
        ENDIF
        IF (ABS(LPP(1)) .GE. 1) THEN
          LP=SIGN(1,LPP(1))
          G2=PDG2PDF(ABS(LPP(1)),0*LP,XBK(1),DSQRT(Q2FACT(1)))
        ENDIF
        PD(0) = 0D0
        IPROC = 0
        IPROC=IPROC+1  ! b g > e+ e- e+ e- b
        PD(IPROC) = B1*G2
        IPROC=IPROC+1  ! c g > e+ e- e+ e- c
        PD(IPROC) = C1*G2
        IPROC=IPROC+1  ! d g > e+ e- e+ e- d
        PD(IPROC) = D1*G2
        IPROC=IPROC+1  ! s g > e+ e- e+ e- s
        PD(IPROC) = S1*G2
        IPROC=IPROC+1  ! u g > e+ e- e+ e- u
        PD(IPROC) = U1*G2
        IPROC=IPROC+1  ! b g > mu+ mu- mu+ mu- b
        PD(IPROC) = B1*G2
        IPROC=IPROC+1  ! c g > mu+ mu- mu+ mu- c
        PD(IPROC) = C1*G2
        IPROC=IPROC+1  ! d g > mu+ mu- mu+ mu- d
        PD(IPROC) = D1*G2
        IPROC=IPROC+1  ! s g > mu+ mu- mu+ mu- s
        PD(IPROC) = S1*G2
        IPROC=IPROC+1  ! u g > mu+ mu- mu+ mu- u
        PD(IPROC) = U1*G2
      ELSE
        IF (ABS(LPP(1)) .GE. 1) THEN
          LP=SIGN(1,LPP(1))
          D1=PDG2PDF(ABS(LPP(1)),1*LP,XBK(1),DSQRT(Q2FACT(1)))
          U1=PDG2PDF(ABS(LPP(1)),2*LP,XBK(1),DSQRT(Q2FACT(1)))
          S1=PDG2PDF(ABS(LPP(1)),3*LP,XBK(1),DSQRT(Q2FACT(1)))
          C1=PDG2PDF(ABS(LPP(1)),4*LP,XBK(1),DSQRT(Q2FACT(1)))
          B1=PDG2PDF(ABS(LPP(1)),5*LP,XBK(1),DSQRT(Q2FACT(1)))
        ENDIF
        IF (ABS(LPP(2)) .GE. 1) THEN
          LP=SIGN(1,LPP(2))
          G2=PDG2PDF(ABS(LPP(2)),0*LP,XBK(2),DSQRT(Q2FACT(2)))
        ENDIF
        PD(0) = 0D0
        IPROC = 0
        IPROC=IPROC+1  ! b g > e+ e- e+ e- b
        PD(IPROC) = B1*G2
        IPROC=IPROC+1  ! c g > e+ e- e+ e- c
        PD(IPROC) = C1*G2
        IPROC=IPROC+1  ! d g > e+ e- e+ e- d
        PD(IPROC) = D1*G2
        IPROC=IPROC+1  ! s g > e+ e- e+ e- s
        PD(IPROC) = S1*G2
        IPROC=IPROC+1  ! u g > e+ e- e+ e- u
        PD(IPROC) = U1*G2
        IPROC=IPROC+1  ! b g > mu+ mu- mu+ mu- b
        PD(IPROC) = B1*G2
        IPROC=IPROC+1  ! c g > mu+ mu- mu+ mu- c
        PD(IPROC) = C1*G2
        IPROC=IPROC+1  ! d g > mu+ mu- mu+ mu- d
        PD(IPROC) = D1*G2
        IPROC=IPROC+1  ! s g > mu+ mu- mu+ mu- s
        PD(IPROC) = S1*G2
        IPROC=IPROC+1  ! u g > mu+ mu- mu+ mu- u
        PD(IPROC) = U1*G2
      ENDIF
      DO I=1,IPROC
        IF (NINCOMING.EQ.2) THEN
          LUM = LUM + PD(I) * CONV
        ELSE
          LUM = LUM + PD(I)
        ENDIF
      ENDDO
      RETURN
      END

