ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTatNLO_U2_2_U3_3_cG_4F_LO_UFO'
     $ //'-full'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_457 = ', GC_457
      WRITE(*,2) 'GC_458 = ', GC_458
      WRITE(*,2) 'GC_460 = ', GC_460
      WRITE(*,2) 'R2GC_694_147 = ', R2GC_694_147
      WRITE(*,2) 'R2GC_709_162 = ', R2GC_709_162
      WRITE(*,2) 'R2GC_900_292 = ', R2GC_900_292
      WRITE(*,2) 'UVGC_1217_229_1eps = ', UVGC_1217_229_1EPS
      WRITE(*,2) 'UVGC_1217_230_1eps = ', UVGC_1217_230_1EPS
      WRITE(*,2) 'UVGC_991_428_1eps = ', UVGC_991_428_1EPS
      WRITE(*,2) 'UVGC_1217_231 = ', UVGC_1217_231
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_197 = ', GC_197
      WRITE(*,2) 'GC_203 = ', GC_203
      WRITE(*,2) 'R2GC_701_154 = ', R2GC_701_154
      WRITE(*,2) 'UVGC_992_429_1eps = ', UVGC_992_429_1EPS
      WRITE(*,2) 'GC_243 = ', GC_243
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_317 = ', GC_317
      WRITE(*,2) 'GC_426 = ', GC_426
      WRITE(*,2) 'GC_535 = ', GC_535
      WRITE(*,2) 'GC_536 = ', GC_536
      WRITE(*,2) 'GC_571 = ', GC_571
      WRITE(*,2) 'GC_573 = ', GC_573
      WRITE(*,2) 'GC_575 = ', GC_575
      WRITE(*,2) 'GC_578 = ', GC_578
      WRITE(*,2) 'GC_588 = ', GC_588
      WRITE(*,2) 'GC_589 = ', GC_589
      WRITE(*,2) 'GC_590 = ', GC_590
      WRITE(*,2) 'GC_591 = ', GC_591
      WRITE(*,2) 'GC_617 = ', GC_617
      WRITE(*,2) 'GC_637 = ', GC_637
      WRITE(*,2) 'GC_638 = ', GC_638
      WRITE(*,2) 'GC_644 = ', GC_644
      WRITE(*,2) 'GC_645 = ', GC_645
      WRITE(*,2) 'GC_647 = ', GC_647
      WRITE(*,2) 'GC_651 = ', GC_651
      WRITE(*,2) 'GC_681 = ', GC_681
      WRITE(*,2) 'GC_683 = ', GC_683
      WRITE(*,2) 'GC_684 = ', GC_684
      WRITE(*,2) 'GC_691 = ', GC_691
