C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjM(-1,1)
C     
      SUBROUTINE MP_FFVS3_4(F1, F2, V3, COUP, M4, W4,S4)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 DENOM
      COMPLEX*32 V3(*)
      COMPLEX*32 P4(0:3)
      COMPLEX*32 TMP7
      COMPLEX*32 F1(*)
      COMPLEX*32 S4(5)
      COMPLEX*32 F2(*)
      REAL*16 M4
      COMPLEX*32 COUP
      REAL*16 W4
      S4(1) = +F1(1)+F2(1)+V3(1)
      S4(2) = +F1(2)+F2(2)+V3(2)
      S4(3) = +F1(3)+F2(3)+V3(3)
      S4(4) = +F1(4)+F2(4)+V3(4)
      P4(0) = -S4(1)
      P4(1) = -S4(2)
      P4(2) = -S4(3)
      P4(3) = -S4(4)
      TMP7 = (F1(5)*(F2(7)*(V3(5)+V3(8))+F2(8)*(V3(6)+CI*(V3(7))))
     $ +F1(6)*(F2(7)*(V3(6)-CI*(V3(7)))+F2(8)*(V3(5)-V3(8))))
      DENOM = COUP/(P4(0)**2-P4(1)**2-P4(2)**2-P4(3)**2 - M4 * (M4 -CI
     $ * W4))
      S4(5)= DENOM*CI * TMP7
      END


