      SUBROUTINE DLUM_5(LUM)
C     ****************************************************            
C         
C     Generated by MadGraph5_aMC@NLO v. 2.6.7, 2019-10-16
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     RETURNS PARTON LUMINOSITIES FOR MADFKS                          
C        
C     
C     Process: g b > h > e+ e- e+ e- b NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: g c > h > e+ e- e+ e- c NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: g d > h > e+ e- e+ e- d NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: g s > h > e+ e- e+ e- s NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: g u > h > e+ e- e+ e- u NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: g b > h > mu+ mu- mu+ mu- b NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: g c > h > mu+ mu- mu+ mu- c NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: g d > h > mu+ mu- mu+ mu- d NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: g s > h > mu+ mu- mu+ mu- s NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     Process: g u > h > mu+ mu- mu+ mu- u NP<=2 QCD<=5 QED<=4
C      WEIGHTED<=28 [ all = QCD ]
C     
C     ****************************************************            
C         
      IMPLICIT NONE
C     
C     CONSTANTS                                                       
C         
C     
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      DOUBLE PRECISION       CONV
      PARAMETER (CONV=389379660D0)  !CONV TO PICOBARNS             
C     
C     ARGUMENTS                                                       
C         
C     
      DOUBLE PRECISION PP(0:3,NEXTERNAL), LUM
C     
C     LOCAL VARIABLES                                                 
C         
C     
      INTEGER I, ICROSS,ITYPE,LP
      DOUBLE PRECISION P1(0:3,NEXTERNAL)
      DOUBLE PRECISION G1
      DOUBLE PRECISION D2,U2,S2,C2,B2
      DOUBLE PRECISION XPQ(-7:7)
C     
C     EXTERNAL FUNCTIONS                                              
C         
C     
      DOUBLE PRECISION ALPHAS2,REWGT,PDG2PDF
C     
C     GLOBAL VARIABLES                                                
C         
C     
      INTEGER              IPROC
      DOUBLE PRECISION PD(0:MAXPROC)
      COMMON /SUBPROC/ PD, IPROC
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
      INTEGER IMIRROR
      COMMON/CMIRROR/IMIRROR
C     
C     DATA                                                            
C         
C     
      DATA G1/1*1D0/
      DATA D2,U2,S2,C2,B2/5*1D0/
      DATA ICROSS/1/
C     ----------                                                      
C         
C     BEGIN CODE                                                      
C         
C     ----------                                                      
C         
      LUM = 0D0
      IF (IMIRROR.EQ.2) THEN
        IF (ABS(LPP(2)) .GE. 1) THEN
          LP=SIGN(1,LPP(2))
          G1=PDG2PDF(ABS(LPP(2)),0*LP,XBK(2),DSQRT(Q2FACT(2)))
        ENDIF
        IF (ABS(LPP(1)) .GE. 1) THEN
          LP=SIGN(1,LPP(1))
          D2=PDG2PDF(ABS(LPP(1)),1*LP,XBK(1),DSQRT(Q2FACT(1)))
          U2=PDG2PDF(ABS(LPP(1)),2*LP,XBK(1),DSQRT(Q2FACT(1)))
          S2=PDG2PDF(ABS(LPP(1)),3*LP,XBK(1),DSQRT(Q2FACT(1)))
          C2=PDG2PDF(ABS(LPP(1)),4*LP,XBK(1),DSQRT(Q2FACT(1)))
          B2=PDG2PDF(ABS(LPP(1)),5*LP,XBK(1),DSQRT(Q2FACT(1)))
        ENDIF
        PD(0) = 0D0
        IPROC = 0
        IPROC=IPROC+1  ! g b > e+ e- e+ e- b
        PD(IPROC) = G1*B2
        IPROC=IPROC+1  ! g c > e+ e- e+ e- c
        PD(IPROC) = G1*C2
        IPROC=IPROC+1  ! g d > e+ e- e+ e- d
        PD(IPROC) = G1*D2
        IPROC=IPROC+1  ! g s > e+ e- e+ e- s
        PD(IPROC) = G1*S2
        IPROC=IPROC+1  ! g u > e+ e- e+ e- u
        PD(IPROC) = G1*U2
        IPROC=IPROC+1  ! g b > mu+ mu- mu+ mu- b
        PD(IPROC) = G1*B2
        IPROC=IPROC+1  ! g c > mu+ mu- mu+ mu- c
        PD(IPROC) = G1*C2
        IPROC=IPROC+1  ! g d > mu+ mu- mu+ mu- d
        PD(IPROC) = G1*D2
        IPROC=IPROC+1  ! g s > mu+ mu- mu+ mu- s
        PD(IPROC) = G1*S2
        IPROC=IPROC+1  ! g u > mu+ mu- mu+ mu- u
        PD(IPROC) = G1*U2
      ELSE
        IF (ABS(LPP(1)) .GE. 1) THEN
          LP=SIGN(1,LPP(1))
          G1=PDG2PDF(ABS(LPP(1)),0*LP,XBK(1),DSQRT(Q2FACT(1)))
        ENDIF
        IF (ABS(LPP(2)) .GE. 1) THEN
          LP=SIGN(1,LPP(2))
          D2=PDG2PDF(ABS(LPP(2)),1*LP,XBK(2),DSQRT(Q2FACT(2)))
          U2=PDG2PDF(ABS(LPP(2)),2*LP,XBK(2),DSQRT(Q2FACT(2)))
          S2=PDG2PDF(ABS(LPP(2)),3*LP,XBK(2),DSQRT(Q2FACT(2)))
          C2=PDG2PDF(ABS(LPP(2)),4*LP,XBK(2),DSQRT(Q2FACT(2)))
          B2=PDG2PDF(ABS(LPP(2)),5*LP,XBK(2),DSQRT(Q2FACT(2)))
        ENDIF
        PD(0) = 0D0
        IPROC = 0
        IPROC=IPROC+1  ! g b > e+ e- e+ e- b
        PD(IPROC) = G1*B2
        IPROC=IPROC+1  ! g c > e+ e- e+ e- c
        PD(IPROC) = G1*C2
        IPROC=IPROC+1  ! g d > e+ e- e+ e- d
        PD(IPROC) = G1*D2
        IPROC=IPROC+1  ! g s > e+ e- e+ e- s
        PD(IPROC) = G1*S2
        IPROC=IPROC+1  ! g u > e+ e- e+ e- u
        PD(IPROC) = G1*U2
        IPROC=IPROC+1  ! g b > mu+ mu- mu+ mu- b
        PD(IPROC) = G1*B2
        IPROC=IPROC+1  ! g c > mu+ mu- mu+ mu- c
        PD(IPROC) = G1*C2
        IPROC=IPROC+1  ! g d > mu+ mu- mu+ mu- d
        PD(IPROC) = G1*D2
        IPROC=IPROC+1  ! g s > mu+ mu- mu+ mu- s
        PD(IPROC) = G1*S2
        IPROC=IPROC+1  ! g u > mu+ mu- mu+ mu- u
        PD(IPROC) = G1*U2
      ENDIF
      DO I=1,IPROC
        IF (NINCOMING.EQ.2) THEN
          LUM = LUM + PD(I) * CONV
        ELSE
          LUM = LUM + PD(I)
        ENDIF
      ENDDO
      RETURN
      END

